# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_rjR5tRI4GFFafUYPcFIm-990Ck-QE8j
"""

!pip install -q streamlit pyvis networkx pandas

import streamlit as st
import pandas as pd
import networkx as nx
from pyvis.network import Network
import streamlit.components.v1 as components

st.title("Redes Complexas Interativas com Pyvis")

uploaded = st.file_uploader("/content/Grafo.csv", type="csv")
if uploaded:
    df = pd.read_csv(uploaded)
    st.write(df.head())

    G = nx.from_pandas_edgelist(df, source='origem', target='destino', edge_attr=True)
    st.write("**Métricas do Grafo:**")
    st.write(f"Nós: {G.number_of_nodes()}, Arestas: {G.number_of_edges()}")
    st.write(f"Grau médio: {sum(dict(G.degree()).values())/G.number_of_nodes():.2f}")
    st.write(f"Coeficiente de agrupamento: {nx.average_clustering(G):.2f}")

    net = Network(notebook=True, width="100%", height="600px")
    net.from_nx(G)
    net.show_buttons(filter_=['physics','nodes','edges'])
    net.save_graph("grafo.html")

    HtmlFile = open("grafo.html", 'r', encoding='utf-8')
    components.html(HtmlFile.read(), height=650, scrolling=True)
